version: "2"
services:
    nginx:
        image: nginx:latest
        ports:
            - "8081:80"
        environment:
            NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
            NGINX_ERROR_LOG_LEVEL: debug
            NGINX_BACKEND_HOST: php
            NGINX_SERVER_ROOT: /var/www/html
        volumes:
            - ./www:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php

    php:
        build: .
        volumes:
            - ./www:/var/www/html
        links:
            - db

    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: petroldb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql

volumes:
    persistent:
